In [1]:
# Import general libraries (needed for functions)
import numpy as np
import time

# Import Qiskit classes
import qiskit 
from qiskit import QuantumRegister, QuantumCircuit, ClassicalRegister, Aer
from qiskit.providers.aer import noise
from qiskit.tools.visualization import plot_histogram

# Import measurement calibration functions
from qiskit.ignis.mitigation.measurement import (complete_meas_cal, tensored_meas_cal,
                                                 CompleteMeasFitter, TensoredMeasFitter)

In [2]:
# Generate the calibration circuits
qr = qiskit.QuantumRegister(5)
qubit_list = [2,3,4]
meas_calibs, state_labels = complete_meas_cal(qubit_list=qubit_list, qr=qr, circlabel='mcal')

In [7]:
meas_calibs[7].draw()

░          
q0_0: ──────░──────────
            ░          
q0_1: ──────░──────────
      ┌───┐ ░ ┌─┐      
q0_2: ┤ X ├─░─┤M├──────
      ├───┤ ░ └╥┘┌─┐   
q0_3: ┤ X ├─░──╫─┤M├───
      ├───┤ ░  ║ └╥┘┌─┐
q0_4: ┤ X ├─░──╫──╫─┤M├
      └───┘ ░  ║  ║ └╥┘
c0: 3/═════════╩══╩══╩═
               0  1  2

In [8]:
# Execute the calibration circuits without noise
backend = qiskit.Aer.get_backend('qasm_simulator')
job = qiskit.execute(meas_calibs, backend=backend, shots=1000)
cal_results = job.result()

In [14]:
?CompleteMeasFitter

Init signature:
CompleteMeasFitter(
    results: Union[qiskit.result.result.Result, List[qiskit.result.result.Result]],
    state_labels: List[str],
    qubit_list: List[int] = None,
    circlabel: str = '',
)
Docstring:      Measurement correction fitter for a full calibration
Init docstring:
Initialize a measurement calibration matrix from the results of running
the circuits returned by `measurement_calibration_circuits`

A wrapper for the tensored fitter

Args:
    results: the results of running the measurement calibration
        circuits. If this is `None` the user will set a calibration
        matrix later.
    state_labels: list of calibration state labels
        returned from `measurement_calibration_circuits`.
        The output matrix will obey this ordering.
    qubit_list: List of the qubits (for reference and if the
        subset is needed). If `None`, the qubit_list will be
        created according to the length of state_labels[0].
    circlabel: if the qubits were l

In [13]:
# The calibration matrix without noise is the identity matrix
meas_fitter = CompleteMeasFitter(cal_results, state_labels, circlabel='mcal')
print(meas_fitter.cal_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
